POST http://localhost:8089/auth/realms/Shiftplanner/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=shiftplanner&username=user&password=user

