version: '3'

volumes:
  lf12_shiftplanner_data:
    driver: local

  lf12_keycloak_data:
    driver: local

services:
  postgres_for_shiftplanner:
    container_name: lf12_shiftplanner
    image: postgres:13.3
    volumes:
      - lf12_shiftplanner_data:/var/lib/postgresql/data
      - ./postgres/start_data.sql:/docker-entrypoint-initdb.d/start_data.sql
    environment:
      POSTGRES_DB: lf12_shiftplanner_db
      POSTGRES_USER: shiftplanner
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_for_keycloak:
    container_name: lf12_keycloakdb_container
    image: postgres:13.3
    volumes:
      - lf12_keycloak_data:/var/lib/postgresql/data/keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/keycloak
    ports:
      - "5433:5433"

  keycloak_for_shiftplanner:
    depends_on:
      - postgres_for_keycloak
    image: jboss/keycloak:12.0.4
    volumes:
      - ./keycloak-realm:/opt/jboss/keycloak/import
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_for_keycloak
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: secret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/opt/jboss/keycloak/import/Shiftplanner-realm.json"
    ports:
      - "8089:8080"